data: ???

module:
  optimizer:
    _target_: torch.optim.Adam
    lr: 1e-3
    betas: [ 0.9, 0.999 ]
    eps: 1e-08
    weight_decay: 0

defaults:
  - _self_
  - data: glucose_data
  - module: glucose_module
